
services:
  api-coordinador:
    build:
      context: ./api-coordinador
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./datos_raw:/datos_raw
    networks:
      - cdc_network


  nodo-ml-1:
    build:
      context: ./nodo-ml
      dockerfile: Dockerfile
    networks:
      - cdc_network


  nodo-ml-2:
    build:
      context: ./nodo-ml
      dockerfile: Dockerfile
    networks:
      - cdc_network


  nodo-ml-3:
    build:
      context: ./nodo-ml
      dockerfile: Dockerfile
    networks:
      - cdc_network


  nodo-ml-4:
    build:
      context: ./nodo-ml
      dockerfile: Dockerfile
    networks:
      - cdc_network


  nodo-ml-5:
    build:
      context: ./nodo-ml
      dockerfile: Dockerfile
    networks:
      - cdc_network


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - cdc_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - cdc_network


networks:
  cdc_network:
    driver: bridge