
services:
  api-coordinador:
    build:
      context: ./api-coordinador
      dockerfile: Dockerfile
    environment:
      - NODOS_ML_ADDRS=nodo-ml-1:9000,nodo-ml-2:9000,nodo-ml-3:9000,nodo-ml-4:9000,nodo-ml-5:9000
      - NUM_WORKERS=12
      - DATASET_PATH=/datos_raw/diabetes_1M_extended.csv
    ports:
      - "8080:8080"
    volumes:
      - ./datos_raw:/datos_raw


  nodo-ml-1:
    build:
      context: ./nodo-ml
      dockerfile: Dockerfile


  nodo-ml-2:
    build:
      context: ./nodo-ml
      dockerfile: Dockerfile


  nodo-ml-3:
    build:
      context: ./nodo-ml
      dockerfile: Dockerfile


  nodo-ml-4:
    build:
      context: ./nodo-ml
      dockerfile: Dockerfile


  nodo-ml-5:
    build:
      context: ./nodo-ml
      dockerfile: Dockerfile


networks:
  cdc_network:
    driver: bridge